apiVersion: v1
kind: ServiceAccount
metadata:
  name: numaflow-dex-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: numaflow-dex-server
    app.kubernetes.io/part-of: numaflow
  name: numaflow-dex-server
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: numaflow-dex-server
    app.kubernetes.io/part-of: numaflow
  name: numaflow-dex-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-dex-server
subjects:
- kind: ServiceAccount
  name: numaflow-dex-server
---
apiVersion: v1
data:
  config.yaml: |-
    connectors:
    - type: github
      # https://dexidp.io/docs/connectors/github/
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        orgs:
        - name: <ORG_NAME>
          teams:
          - admin
          - readonly
kind: ConfigMap
metadata:
  name: numaflow-dex-server-config
---
apiVersion: v1
kind: Secret
metadata:
  name: numaflow-dex-secrets
stringData:
  dex-github-client-id: <GITHUB_CLIENT_ID>
  dex-github-client-secret: <GITHUB_CLIENT_SECRET>
---
apiVersion: v1
kind: Service
metadata:
  name: numaflow-dex-server
spec:
  ports:
  - port: 5556
    targetPort: 5556
  selector:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: numaflow-dex-server
    app.kubernetes.io/part-of: numaflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/name: numaflow-dex-server
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dex-server
        app.kubernetes.io/name: numaflow-dex-server
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
      - command:
        - /usr/local/bin/dex
        - serve
        - /etc/numaflow/dex/cfg/config.yaml
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: dex-github-client-id
              name: numaflow-dex-secrets
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: dex-github-client-secret
              name: numaflow-dex-secrets
        image: dexidp/dex:v2.37.0
        imagePullPolicy: Always
        name: dex
        ports:
        - containerPort: 5556
        volumeMounts:
        - mountPath: /etc/numaflow/dex/cfg/config.yaml
          name: generated-dex-config
          subPath: config.yaml
        - mountPath: /etc/numaflow/dex/tls/tls.crt
          name: tls
          subPath: tls.crt
        - mountPath: /etc/numaflow/dex/tls/tls.key
          name: tls
          subPath: tls.key
      initContainers:
      - args:
        - dex-server-init
        env:
        - name: NUMAFLOW_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: server.address
              name: numaflow-cmd-params-config
              optional: true
        - name: NUMAFLOW_SERVER_BASE_HREF
          valueFrom:
            configMapKeyRef:
              key: server.base.href
              name: numaflow-cmd-params-config
              optional: true
        image: quay.io/numaproj/numaflow:latest
        imagePullPolicy: Always
        name: dex-init
        volumeMounts:
        - mountPath: /cfg
          name: connector-config
        - mountPath: /tls
          name: tls
        - mountPath: /tmp
          name: generated-dex-config
      serviceAccountName: numaflow-dex-server
      volumes:
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: numaflow-dex-server-config
        name: connector-config
      - emptyDir: {}
        name: tls
      - emptyDir: {}
        name: generated-dex-config
